### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by edysegura** [chls84/projeto#3]
It is not possible to access the services due the timeout issue.

![image](https://cloud.githubusercontent.com/assets/5324414/10885395/2d245938-8164-11e5-9340-64b7a9e145bd.png)

**Comment by renataakemi** [comment]
Hi Edy,

This is not our page. Our project is hosted on http://renatakemi.tk
I have just tested it and it is working fine.
Please let us not if is ok now.

Thanks,
Renata

**Comment by edysegura** [comment]
Ohw! I'm sorry! I've opened it wrong. My bad!
