### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by edysegura** [chls84/projeto#5]
It was possible to retrieve all deliverable without any authentication.

![image](https://cloud.githubusercontent.com/assets/5324414/10894694/57fcfd12-8197-11e5-86a3-ab16dc8ea6a4.png)

**Comment by chls84** [comment]
If you already logged in http://renatakemi.tk:3000/api, you will able to use post/get/put/post. But if not logged is not possible. We use Basic authentication in /api.

**Comment by edysegura** [comment]
Hi @chls84! That is not the case, I've connect to your API from a Linux box without any authentication.

**Comment by chls84** [comment]
Yes, I just tested here and in internet explorer without authentication,
but in google chrome only fetch if is already authenticated.


2015-11-03 10:31 GMT-02:00 Edy Segura <notifications@github.com>:
