### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by edysegura** [chls84/projeto#7]
How can we check the reports?

![image](https://cloud.githubusercontent.com/assets/5324414/10895160/d4970d70-8199-11e5-9536-4b06bf7fa1dc.png)

**Comment by chls84** [comment]
We had a problem with this report. Only way to test report is using Google Chrome with following command: "chrome --disable-web-security". 
Every time we access the report page, page asks for header, we set the header but seems there is not effect.

**Comment by edysegura** [comment]
What you might need is to enable [CORS](http://enable-cors.org/) to your API application. Look this module: https://github.com/expressjs/cors

**Comment by chls84** [comment]
Yes, I teste in Internet Explorer and works fine.
![image](https://cloud.githubusercontent.com/assets/12371479/10909330/86abec94-821f-11e5-808e-d6f400cd02bc.png)

**Comment by edysegura** [comment]
Thanks to let me know!
